export type Plan = "starter" | "growth" | "pro" | "enterprise";
export type OrgRole = "owner" | "admin" | "member";
export type StoreCategory = "core" | "integration" | "industry" | "community" | "premium";

export const PLANS: Record<Plan, { label: string; price: number; modules: string[] }> = {
  starter:    { label: "Starter",    price: 29,  modules: ["crm"] },
  growth:     { label: "Growth",     price: 79,  modules: ["crm", "inventory"] },
  pro:        { label: "Pro",        price: 149, modules: ["crm", "inventory", "accounting", "hr"] },
  enterprise: { label: "Enterprise", price: 299, modules: ["crm", "inventory", "accounting", "hr", "projects", "reports"] },
};

export interface ModuleMeta {
  key: string;
  name: string;
  description: string;
  longDescription: string;
  icon: string;
  requiredPlan: Plan;
  category: StoreCategory;
  version: string;
  author: string;
  rating: number;
  reviewCount: number;
  tags: string[];
  features: string[];
  price: number | null;
  isComingSoon?: boolean;
}

export const MODULE_REGISTRY: ModuleMeta[] = [
  // ── CORE MODULES ──────────────────────────────────────────────────────────
  {
    key: "crm",
    name: "CRM",
    description: "Manage leads, deals, and customers in one pipeline.",
    longDescription: "A full-featured customer relationship management system. Track leads through your pipeline, manage deals with kanban views, and maintain a complete customer database with activity logs, email tracking, and conversion analytics.",
    icon: "Users",
    requiredPlan: "starter",
    category: "core",
    version: "1.2.0",
    author: "Business360",
    rating: 4.8,
    reviewCount: 124,
    tags: ["sales", "leads", "pipeline", "customers"],
    features: ["Lead management", "Deal pipeline (Kanban)", "Customer database", "Activity logs", "Conversion analytics", "Email tracking"],
    price: null,
  },
  {
    key: "inventory",
    name: "Inventory",
    description: "Track stock levels, warehouses, and transfers.",
    longDescription: "Complete inventory management solution. Track stock in real-time across multiple warehouses, manage product variants, handle transfers, and set reorder alerts to prevent stockouts.",
    icon: "Boxes",
    requiredPlan: "growth",
    category: "core",
    version: "1.1.0",
    author: "Business360",
    rating: 4.6,
    reviewCount: 89,
    tags: ["stock", "warehouse", "products", "transfers"],
    features: ["Real-time stock tracking", "Multi-warehouse support", "Product variants", "Stock transfers", "Reorder alerts", "Barcode scanning"],
    price: null,
  },
  {
    key: "accounting",
    name: "Accounting",
    description: "Invoices, expenses, and financial reports.",
    longDescription: "Professional accounting suite with full double-entry bookkeeping. Create invoices, track expenses, reconcile bank statements, and generate P&L, balance sheet, and cash flow reports.",
    icon: "Calculator",
    requiredPlan: "pro",
    category: "core",
    version: "1.0.5",
    author: "Business360",
    rating: 4.7,
    reviewCount: 67,
    tags: ["finance", "invoices", "expenses", "reports"],
    features: ["Double-entry bookkeeping", "Invoice generation", "Expense tracking", "Bank reconciliation", "P&L reports", "Tax management"],
    price: null,
  },
  {
    key: "hr",
    name: "HR",
    description: "Manage employees, leave requests, and contracts.",
    longDescription: "Full human resources management. Handle the entire employee lifecycle from hiring to offboarding — leave requests, attendance, contracts, payroll, and org chart.",
    icon: "UserCheck",
    requiredPlan: "pro",
    category: "core",
    version: "1.0.3",
    author: "Business360",
    rating: 4.5,
    reviewCount: 52,
    tags: ["employees", "payroll", "leave", "contracts"],
    features: ["Employee profiles", "Leave management", "Contract tracking", "Attendance tracking", "Payroll processing", "Org chart"],
    price: null,
  },
  {
    key: "projects",
    name: "Projects",
    description: "Tasks, milestones, and team collaboration.",
    longDescription: "Project management built for modern teams. Kanban, Gantt, and list views with time tracking, milestone alerts, and team collaboration built in.",
    icon: "Package",
    requiredPlan: "enterprise",
    category: "core",
    version: "1.0.1",
    author: "Business360",
    rating: 4.4,
    reviewCount: 38,
    tags: ["tasks", "projects", "gantt", "collaboration"],
    features: ["Kanban boards", "Gantt charts", "Task assignments", "Milestone tracking", "Time logging", "Team collaboration"],
    price: null,
  },
  {
    key: "reports",
    name: "Reports",
    description: "KPI dashboards, cross-module analytics, and exports.",
    longDescription: "Business intelligence across all modules. Build custom KPI dashboards, schedule automated reports, and export in PDF/Excel. Cross-module analytics give you a 360° view.",
    icon: "BarChart3",
    requiredPlan: "enterprise",
    category: "core",
    version: "1.0.0",
    author: "Business360",
    rating: 4.6,
    reviewCount: 29,
    tags: ["analytics", "dashboards", "kpi", "exports"],
    features: ["Custom KPI dashboards", "Cross-module analytics", "Scheduled reports", "PDF/Excel exports", "Real-time data", "Pivot tables"],
    price: null,
  },
  // ── INTEGRATIONS ──────────────────────────────────────────────────────────
  {
    key: "stripe",
    name: "Stripe Payments",
    description: "Accept online payments directly inside Business360.",
    longDescription: "Connect Stripe and start accepting payments right from your invoices. Supports one-time payments, subscriptions, and automated reconciliation with Accounting.",
    icon: "CreditCard",
    requiredPlan: "growth",
    category: "integration",
    version: "1.0.0",
    author: "Business360",
    rating: 4.9,
    reviewCount: 203,
    tags: ["payments", "stripe", "invoicing", "subscriptions"],
    features: ["One-click payment links", "Subscription billing", "Auto-reconciliation", "Refund management", "Webhook sync", "Multi-currency"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "slack",
    name: "Slack Notifications",
    description: "Send real-time alerts and updates to your Slack workspace.",
    longDescription: "Get instant Slack notifications for new leads, won deals, paid invoices, and low stock — delivered to the right channel with full context.",
    icon: "MessageSquare",
    requiredPlan: "starter",
    category: "integration",
    version: "1.0.0",
    author: "Business360",
    rating: 4.7,
    reviewCount: 156,
    tags: ["notifications", "slack", "alerts", "team"],
    features: ["Custom alert rules", "Channel routing", "Rich message cards", "Bi-directional sync", "Command shortcuts", "Digest reports"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "whatsapp",
    name: "WhatsApp Business",
    description: "Communicate with customers via WhatsApp from your CRM.",
    longDescription: "Turn WhatsApp into a sales and support channel. Send messages from CRM records, manage conversations, auto-reply, and track all interactions in the activity log.",
    icon: "Phone",
    requiredPlan: "growth",
    category: "integration",
    version: "0.9.0",
    author: "Business360",
    rating: 4.5,
    reviewCount: 87,
    tags: ["whatsapp", "messaging", "crm", "support"],
    features: ["Send/receive messages", "Template messages", "Auto-replies", "CRM integration", "Conversation history", "Bulk messaging"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "zapier",
    name: "Zapier",
    description: "Connect Business360 to 6,000+ apps via Zapier.",
    longDescription: "Automate your workflow by connecting Business360 to any app in the Zapier ecosystem. Trigger on any event and automate actions across your entire stack.",
    icon: "Zap",
    requiredPlan: "pro",
    category: "integration",
    version: "1.0.0",
    author: "Business360",
    rating: 4.8,
    reviewCount: 312,
    tags: ["automation", "zapier", "integration", "workflow"],
    features: ["6000+ app connections", "Trigger on any event", "Custom Zap builder", "Multi-step Zaps", "Error handling", "Webhook support"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "google-workspace",
    name: "Google Workspace",
    description: "Sync contacts, calendar, and Drive with Business360.",
    longDescription: "Deep integration with Google Workspace — sync CRM contacts with Gmail, calendar events with Projects, and documents with Drive. SSO login included.",
    icon: "Globe",
    requiredPlan: "starter",
    category: "integration",
    version: "1.1.0",
    author: "Business360",
    rating: 4.6,
    reviewCount: 178,
    tags: ["google", "calendar", "drive", "sso"],
    features: ["Gmail sync", "Calendar integration", "Drive attachments", "SSO login", "Contact sync", "Meet links in tasks"],
    price: null,
    isComingSoon: true,
  },
  // ── INDUSTRY PACKS ────────────────────────────────────────────────────────
  {
    key: "retail",
    name: "Retail Suite",
    description: "Point of sale, loyalty programs, and retail analytics.",
    longDescription: "Everything a retail business needs: POS, customer loyalty, gift cards, and retail analytics — all integrated with Inventory and Accounting.",
    icon: "ShoppingCart",
    requiredPlan: "pro",
    category: "industry",
    version: "1.0.0",
    author: "Business360",
    rating: 4.6,
    reviewCount: 45,
    tags: ["retail", "pos", "loyalty", "ecommerce"],
    features: ["Point of Sale", "Loyalty programs", "Gift cards", "Product catalog", "Retail analytics", "Multi-location POS"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "logistics",
    name: "Logistics Suite",
    description: "Fleet management, route planning, and delivery tracking.",
    longDescription: "Built for logistics companies. Manage fleet, plan optimal routes, track deliveries in real-time, and provide customers live ETAs. Integrates with Inventory.",
    icon: "Truck",
    requiredPlan: "pro",
    category: "industry",
    version: "0.9.0",
    author: "Business360",
    rating: 4.3,
    reviewCount: 28,
    tags: ["logistics", "fleet", "delivery", "routes"],
    features: ["Fleet management", "Route optimization", "Real-time tracking", "Customer notifications", "Driver app", "Delivery analytics"],
    price: null,
    isComingSoon: true,
  },
  {
    key: "healthcare",
    name: "Healthcare Suite",
    description: "Patient records, appointments, and clinic management.",
    longDescription: "Compliance-ready healthcare management. Patient records, appointment scheduling, billing, and clinic analytics — built for healthcare providers.",
    icon: "Activity",
    requiredPlan: "enterprise",
    category: "industry",
    version: "0.8.0",
    author: "Business360",
    rating: 4.4,
    reviewCount: 19,
    tags: ["healthcare", "patients", "clinic", "appointments"],
    features: ["Patient records", "Appointment scheduling", "Prescription tracking", "Billing integration", "HIPAA-ready", "Analytics dashboard"],
    price: null,
    isComingSoon: true,
  },
  // ── PREMIUM ───────────────────────────────────────────────────────────────
  {
    key: "ai-assistant",
    name: "AI Business Assistant",
    description: "AI-powered insights, auto-reports, and smart predictions.",
    longDescription: "Your personal AI business advisor. Natural language queries, auto-generated reports, anomaly detection, and predictive forecasts — powered by state-of-the-art LLMs.",
    icon: "Sparkles",
    requiredPlan: "pro",
    category: "premium",
    version: "2.0.0",
    author: "Business360",
    rating: 4.9,
    reviewCount: 521,
    tags: ["ai", "insights", "predictions", "automation"],
    features: ["Natural language queries", "Auto-generated reports", "Anomaly detection", "Revenue forecasting", "Churn prediction", "Smart recommendations"],
    price: 49,
    isComingSoon: true,
  },
  {
    key: "advanced-analytics",
    name: "Advanced Analytics",
    description: "Cohort analysis, funnels, and custom metric builder.",
    longDescription: "Go beyond standard reports. Build cohort analyses, funnel reports, and custom metrics spanning multiple modules. Share dashboards with stakeholders.",
    icon: "TrendingUp",
    requiredPlan: "growth",
    category: "premium",
    version: "1.5.0",
    author: "Business360",
    rating: 4.7,
    reviewCount: 189,
    tags: ["analytics", "cohorts", "funnels", "metrics"],
    features: ["Cohort analysis", "Funnel tracking", "Custom metric builder", "Automated delivery", "Shareable dashboards", "Data export API"],
    price: 29,
    isComingSoon: true,
  },
];
